# Seasonality Modeling of Timeseries Data

In [ ]:
import numpy as np
import pandas as pd
from statsmodels.tsa.seasonal import seasonal_decompose
import matplotlib.pyplot as plt

In [16]:
#corrected data with means for each group of 5 animals
wnt_data_corrected = pd.read_csv("wnt_corrected.csv")
#unique indexes for sanity checking
wnt_data_corrected.index = wnt_data_corrected["gene"] + wnt_data_corrected["Time.Point"].apply(lambda x: x.replace("Day ", "D."))
#get relative error bar positions values as offsets of means
wnt_data_corrected["lower_err"] = abs(wnt_data_corrected["lower"] - wnt_data_corrected["mean"])
wnt_data_corrected["upper_err"] = abs(wnt_data_corrected["upper"] - wnt_data_corrected["mean"])
del wnt_data_corrected["Unnamed: 0"]

wnt_data_corrected

,gene,Time.Point,mean,sd,lower,upper,lower_err,upper_err
wnt9D.1,wnt9,Day 1,0.138649,0.211341,-0.200350,0.473402,0.338999,0.334753
wnt9D.14,wnt9,Day 14,0.257552,0.211944,-0.083801,0.600797,0.341353,0.343245
wnt9D.21,wnt9,Day 21,-0.071788,0.213450,-0.428650,0.281111,0.356861,0.352899
wnt9D.3,wnt9,Day 3,0.771689,0.215710,0.408644,1.121518,0.363045,0.349830
wnt9D.5,wnt9,Day 5,0.462917,0.214714,0.120594,0.832663,0.342323,0.369746
wnt9D.7,wnt9,Day 7,0.302412,0.216310,-0.043544,0.655283,0.345956,0.352871
wnt6D.1,wnt6,Day 1,-0.620026,0.367346,-1.195549,-0.041525,0.575524,0.578501
wnt6D.14,wnt6,Day 14,0.958533,0.368885,0.362158,1.553291,0.596375,0.594759
wnt6D.21,wnt6,Day 21,0.770463,0.371845,0.153110,1.382216,0.617353,0.611753
wnt6D.3,wnt6,Day 3,1.381159,0.361248,0.788282,1.963123,0.592877,0.581964
wnt6D.5,wnt6,Day 5,1.045624,0.401922,0.442179,1.703280,0.603445,0.657657
wnt6D.7,wnt6,Day 7,0.920085,0.359672,0.370250,1.550691,0.549835,0.630606
wnt3aD.1,wnt3a,Day 1,0.202602,0.207449,-0.152520,0.544752,0.355122,0.342150
wnt3aD.14,wnt3a,Day 14,-0.268129,0.212306,-0.620470,0.077620,0.352342,0.345749
wnt3aD.21,wnt3a,Day 21,-0.680927,0.214195,-1.028540,-0.318630,0.347614,0.362296
wnt3aD.3,wnt3a,Day 3,0.442483,0.211921,0.087139,0.795079,0.355344,0.352597
wnt3aD.5,wnt3a,Day 5,-0.137683,0.201241,-0.477066,0.193004,0.339383,0.330687
wnt3aD.7,wnt3a,Day 7,-0.252799,0.209880,-0.622521,0.094160,0.369721,0.346959
wnt4D.1,wnt4,Day 1,-0.325081,0.286823,-0.804058,0.145625,0.478977,0.470706
wnt4D.14,wnt4,Day 14,0.466613,0.283882,0.006590,0.902649,0.460022,0.436037
wnt4D.21,wnt4,Day 21,0.594180,0.286130,0.145561,1.084662,0.448619,0.490482
wnt4D.3,wnt4,Day 3,0.351508,0.284255,-0.086517,0.803968,0.438025,0.452460
wnt4D.5,wnt4,Day 5,0.574805,0.279099,0.132549,1.044875,0.442256,0.470070
wnt4D.7,wnt4,Day 7,0.047105,0.280156,-0.407201,0.507715,0.454306,0.460609
wnt5bD.1,wnt5b,Day 1,-1.072670,0.293854,-1.551130,-0.596138,0.478460,0.476532
wnt5bD.14,wnt5b,Day 14,1.127846,0.303593,0.629977,1.618114,0.497869,0.490269
wnt5bD.21,wnt5b,Day 21,0.879089,0.293631,0.407025,1.361163,0.472064,0.482074
wnt5bD.3,wnt5b,Day 3,0.168831,0.294365,-0.314213,0.669529,0.483044,0.500698
wnt5bD.5,wnt5b,Day 5,0.836197,0.292437,0.343361,1.291928,0.492835,0.455731
wnt5bD.7,wnt5b,Day 7,0.165922,0.301831,-0.328452,0.659391,0.494373,0.493469
wnt10bD.1,wnt10b,Day 1,-0.556617,0.309250,-1.058840,-0.052382,0.502223,0.504235
wnt10bD.14,wnt10b,Day 14,0.989542,0.312217,0.457758,1.500315,0.531784,0.510773
wnt10bD.21,wnt10b,Day 21,0.748339,0.301974,0.253932,1.209126,0.494408,0.460787
wnt10bD.3,wnt10b,Day 3,0.726185,0.305833,0.215352,1.208699,0.510833,0.482514
wnt10bD.5,wnt10b,Day 5,0.696268,0.306699,0.196171,1.186736,0.500096,0.490468
wnt10bD.7,wnt10b,Day 7,0.213136,0.314181,-0.292573,0.736869,0.505709,0.523733
wnt16D.1,wnt16,Day 1,-0.457546,0.319510,-0.991393,0.065830,0.533847,0.523376
wnt16D.14,wnt16,Day 14,0.387129,0.319892,-0.132128,0.911287,0.519257,0.524157
wnt16D.21,wnt16,Day 21,0.248367,0.332127,-0.272146,0.789827,0.520513,0.541460
wnt16D.3,wnt16,Day 3,0.732665,0.313768,0.219357,1.251932,0.513308,0.519267
wnt16D.5,wnt16,Day 5,0.487854,0.321195,-0.032279,1.011602,0.520133,0.523748
wnt16D.7,wnt16,Day 7,-0.364924,0.324851,-0.904363,0.159470,0.539439,0.524394

In [17]:
## Rename Time.Point to time_point and derive days as numbers
wnt_data_corrected['time_point'] = wnt_data_corrected['Time.Point'].str.replace("Day ", "", regex=False)
wnt_data_corrected['time_point'] = wnt_data_corrected['time_point'].astype(int)

## Turn time_point into a date 1/X/2025
wnt_data_corrected['date'] = pd.to_datetime("2024-12-31") + pd.to_timedelta(wnt_data_corrected['time_point'], unit='D')

## Drop Time.Point columns
wnt_data_corrected = wnt_data_corrected.drop(columns=['Time.Point', 'time_point'])

wnt_data_corrected.head()

,gene,mean,sd,lower,upper,lower_err,upper_err,date
wnt9D.1,wnt9,0.138649,0.211341,-0.200350,0.473402,0.338999,0.334753,2025-01-01
wnt9D.14,wnt9,0.257552,0.211944,-0.083801,0.600797,0.341353,0.343245,2025-01-14
wnt9D.21,wnt9,-0.071788,0.213450,-0.428650,0.281111,0.356861,0.352899,2025-01-21
wnt9D.3,wnt9,0.771689,0.215710,0.408644,1.121518,0.363045,0.349830,2025-01-03
wnt9D.5,wnt9,0.462917,0.214714,0.120594,0.832663,0.342323,0.369746,2025-01-05

In [18]:
wnt_data_corrected = wnt_data_corrected.set_index('date')

wnt_data_corrected.index = pd.PeriodIndex(wnt_data_corrected.index, freq='D')

wnt_data_corrected

,gene,mean,sd,lower,upper,lower_err,upper_err
date,,,,,,,
2025-01-01,wnt9,0.138649,0.211341,-0.200350,0.473402,0.338999,0.334753
2025-01-14,wnt9,0.257552,0.211944,-0.083801,0.600797,0.341353,0.343245
2025-01-21,wnt9,-0.071788,0.213450,-0.428650,0.281111,0.356861,0.352899
2025-01-03,wnt9,0.771689,0.215710,0.408644,1.121518,0.363045,0.349830
2025-01-05,wnt9,0.462917,0.214714,0.120594,0.832663,0.342323,0.369746
2025-01-07,wnt9,0.302412,0.216310,-0.043544,0.655283,0.345956,0.352871
2025-01-01,wnt6,-0.620026,0.367346,-1.195549,-0.041525,0.575524,0.578501
2025-01-14,wnt6,0.958533,0.368885,0.362158,1.553291,0.596375,0.594759
2025-01-21,wnt6,0.770463,0.371845,0.153110,1.382216,0.617353,0.611753
2025-01-03,wnt6,1.381159,0.361248,0.788282,1.963123,0.592877,0.581964
2025-01-05,wnt6,1.045624,0.401922,0.442179,1.703280,0.603445,0.657657
2025-01-07,wnt6,0.920085,0.359672,0.370250,1.550691,0.549835,0.630606
2025-01-01,wnt3a,0.202602,0.207449,-0.152520,0.544752,0.355122,0.342150
2025-01-14,wnt3a,-0.268129,0.212306,-0.620470,0.077620,0.352342,0.345749
2025-01-21,wnt3a,-0.680927,0.214195,-1.028540,-0.318630,0.347614,0.362296
2025-01-03,wnt3a,0.442483,0.211921,0.087139,0.795079,0.355344,0.352597
2025-01-05,wnt3a,-0.137683,0.201241,-0.477066,0.193004,0.339383,0.330687
2025-01-07,wnt3a,-0.252799,0.209880,-0.622521,0.094160,0.369721,0.346959
2025-01-01,wnt4,-0.325081,0.286823,-0.804058,0.145625,0.478977,0.470706
2025-01-14,wnt4,0.466613,0.283882,0.006590,0.902649,0.460022,0.436037
2025-01-21,wnt4,0.594180,0.286130,0.145561,1.084662,0.448619,0.490482
2025-01-03,wnt4,0.351508,0.284255,-0.086517,0.803968,0.438025,0.452460
2025-01-05,wnt4,0.574805,0.279099,0.132549,1.044875,0.442256,0.470070
2025-01-07,wnt4,0.047105,0.280156,-0.407201,0.507715,0.454306,0.460609
2025-01-01,wnt5b,-1.072670,0.293854,-1.551130,-0.596138,0.478460,0.476532
2025-01-14,wnt5b,1.127846,0.303593,0.629977,1.618114,0.497869,0.490269
2025-01-21,wnt5b,0.879089,0.293631,0.407025,1.361163,0.472064,0.482074
2025-01-03,wnt5b,0.168831,0.294365,-0.314213,0.669529,0.483044,0.500698
2025-01-05,wnt5b,0.836197,0.292437,0.343361,1.291928,0.492835,0.455731
2025-01-07,wnt5b,0.165922,0.301831,-0.328452,0.659391,0.494373,0.493469
2025-01-01,wnt10b,-0.556617,0.309250,-1.058840,-0.052382,0.502223,0.504235
2025-01-14,wnt10b,0.989542,0.312217,0.457758,1.500315,0.531784,0.510773
2025-01-21,wnt10b,0.748339,0.301974,0.253932,1.209126,0.494408,0.460787
2025-01-03,wnt10b,0.726185,0.305833,0.215352,1.208699,0.510833,0.482514
2025-01-05,wnt10b,0.696268,0.306699,0.196171,1.186736,0.500096,0.490468
2025-01-07,wnt10b,0.213136,0.314181,-0.292573,0.736869,0.505709,0.523733
2025-01-01,wnt16,-0.457546,0.319510,-0.991393,0.065830,0.533847,0.523376
2025-01-14,wnt16,0.387129,0.319892,-0.132128,0.911287,0.519257,0.524157
2025-01-21,wnt16,0.248367,0.332127,-0.272146,0.789827,0.520513,0.541460
2025-01-03,wnt16,0.732665,0.313768,0.219357,1.251932,0.513308,0.519267
2025-01-05,wnt16,0.487854,0.321195,-0.032279,1.011602,0.520133,0.523748
2025-01-07,wnt16,-0.364924,0.324851,-0.904363,0.159470,0.539439,0.524394

In [13]:
def get_gene_data(gene_name:str) -> pd.DataFrame:
    gene_data = wnt_data_corrected[wnt_data_corrected['gene'] == gene_name].copy()[['mean']]
    gene_data.index = pd.PeriodIndex(gene_data.index, freq='D')
    return gene_data

# wnt9_data = wnt_data_pvt[wnt_data_pvt['gene'] == 'wnt9'].copy()[['count']]
# wnt9_data = wnt_data_pvt[wnt_data_pvt['gene'] == 'wnt9'].copy()[['count']]

# wnt9_data

## Time Series Decomposition

Time series decomposition divides the data into its trend, seasonal, and residual components.

In [19]:
## Perform time series decomposition
## Genes: ['wnt9', 'tubb', 'ubc', 'tuba', 'wnt3a', 'wnt6', 'wnt4', 'wnt5b', 'wnt10b', 'wnt16']

wnt3a_decomp = seasonal_decompose(get_gene_data('wnt3a'), model='stl', period=1)
wnt6_decomp = seasonal_decompose(get_gene_data('wnt6'), model='stl', period=1)
wnt4_decomp = seasonal_decompose(get_gene_data('wnt4'), model='stl', period=1)
wnt5b_decomp = seasonal_decompose(get_gene_data('wnt5b'), model='stl', period=1)
wnt9_decomp = seasonal_decompose(get_gene_data('wnt9'), model='stl', period=1)
wnt10b_decomp = seasonal_decompose(get_gene_data('wnt10b'), model='stl', period=1)
wnt16_decomp = seasonal_decompose(get_gene_data('wnt16'), model='stl', period=1)
# tubb_decomp = seasonal_decompose(get_gene_data('tubb'), model='stl', period=1)
# ubc_decomp = seasonal_decompose(get_gene_data('ubc'), model='stl', period=1)
# tuba_decomp = seasonal_decompose(get_gene_data('tuba'), model='stl', period=1)

In [20]:
wnt_decomp_df = pd.DataFrame({
    "resid_wnt9": wnt9_decomp.resid,
    "seasonal_wnt9": wnt9_decomp.seasonal,
    "trend_wnt9": wnt9_decomp.trend,
    "weights_wnt9": wnt9_decomp.weights,
    # "resid_tubb": tubb_decomp.resid,
    # "seasonal_tubb": tubb_decomp.seasonal,
    # "trend_tubb": tubb_decomp.trend,
    # "weights_tubb": tubb_decomp.weights,
    # "resid_ubc": ubc_decomp.resid,
    # "seasonal_ubc": ubc_decomp.seasonal,
    # "trend_ubc": ubc_decomp.trend,
    # "weights_ubc": ubc_decomp.weights,
    # "resid_tuba": tuba_decomp.resid,
    # "seasonal_tuba": tuba_decomp.seasonal,
    # "trend_tuba": tuba_decomp.trend,
    # "weights_tuba": tuba_decomp.weights,
    "resid_wnt3a": wnt3a_decomp.resid,
    "seasonal_wnt3a": wnt3a_decomp.seasonal,
    "trend_wnt3a": wnt3a_decomp.trend,
    "weights_wnt3a": wnt3a_decomp.weights,
    "resid_wnt6": wnt6_decomp.resid,
    "seasonal_wnt6": wnt6_decomp.seasonal,
    "trend_wnt6": wnt6_decomp.trend,
    "weights_wnt6": wnt6_decomp.weights,
    "resid_wnt4": wnt4_decomp.resid,
    "seasonal_wnt4": wnt4_decomp.seasonal,
    "trend_wnt4": wnt4_decomp.trend,
    "weights_wnt4": wnt4_decomp.weights,
    "resid_wnt5b": wnt5b_decomp.resid,
    "seasonal_wnt5b": wnt5b_decomp.seasonal,
    "trend_wnt5b": wnt5b_decomp.trend,
    "weights_wnt5b": wnt5b_decomp.weights,
    "resid_wnt10b": wnt10b_decomp.resid,
    "seasonal_wnt10b": wnt10b_decomp.seasonal,
    "trend_wnt10b": wnt10b_decomp.trend,
    "weights_wnt10b": wnt10b_decomp.weights,
    "resid_wnt16": wnt16_decomp.resid,
    "seasonal_wnt16": wnt16_decomp.seasonal,
    "trend_wnt16": wnt16_decomp.trend,
    "weights_wnt16": wnt16_decomp.weights,
})

## Rename index to 'date' for consistency
wnt_decomp_df.index.name = 'date'
## Turn index into a column
wnt_decomp_df.reset_index(inplace=True)

wnt_decomp_df.head()

,date,resid_wnt9,seasonal_wnt9,trend_wnt9,weights_wnt9,resid_wnt3a,seasonal_wnt3a,trend_wnt3a,weights_wnt3a,resid_wnt6,...,trend_wnt5b,weights_wnt5b,resid_wnt10b,seasonal_wnt10b,trend_wnt10b,weights_wnt10b,resid_wnt16,seasonal_wnt16,trend_wnt16,weights_wnt16
0,2025-01-01,0.0,0.0,0.138649,1.0,0.0,0.0,0.202602,1.0,0.0,...,-1.072670,1.0,0.0,0.0,-0.556617,1.0,0.0,0.0,-0.457546,1.0
1,2025-01-14,0.0,0.0,0.257552,1.0,0.0,0.0,-0.268129,1.0,0.0,...,1.127846,1.0,0.0,0.0,0.989542,1.0,0.0,0.0,0.387129,1.0
2,2025-01-21,0.0,0.0,-0.071788,1.0,0.0,0.0,-0.680927,1.0,0.0,...,0.879089,1.0,0.0,0.0,0.748339,1.0,0.0,0.0,0.248367,1.0
3,2025-01-03,0.0,0.0,0.771689,1.0,0.0,0.0,0.442483,1.0,0.0,...,0.168831,1.0,0.0,0.0,0.726185,1.0,0.0,0.0,0.732665,1.0
4,2025-01-05,0.0,0.0,0.462917,1.0,0.0,0.0,-0.137683,1.0,0.0,...,0.836197,1.0,0.0,0.0,0.696268,1.0,0.0,0.0,0.487854,1.0

In [21]:
wnt_decomp_df_long = pd.wide_to_long(wnt_decomp_df, stubnames=['resid', 'seasonal', 'trend', 'weights'], i=['date'], j='set', sep='_', suffix=r'\w+')

wnt_decomp_df_long.head()

                 resid  seasonal     trend  weights
date       set
2025-01-01 wnt9    0.0       0.0  0.138649      1.0
2025-01-14 wnt9    0.0       0.0  0.257552      1.0
2025-01-21 wnt9    0.0       0.0 -0.071788      1.0
2025-01-03 wnt9    0.0       0.0  0.771689      1.0
2025-01-05 wnt9    0.0       0.0  0.462917      1.0

In [22]:
wnt_decomp_df_long.to_csv("wnt_corrected_decomp_df_long.csv")